### ISSUE TITLE
Performance issue with pgRouting 2.2.0 pgr_dijkstra

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#526]
### Expected behavior and actual behavior

I was going thru the book examples and I'm noticing some major performance degradataion.  
Not sure where its coming from. 

### Steps to reproduce the problem
I have this query in Part 2 importing OSM data:
`

SELECT r.seq, r.node, w.name As street, r.cost,
( SUM(w.length_m) OVER(ORDER BY r.seq) )::numeric(10,2) As dist_m
 FROM pgr_dijkstra('SELECT gid AS id,
 source,
 target,
 cost, reverse_cost
 FROM ospr.ways',
 pgr_pointToEdgeNode('ospr.ways', ST_SetSRID( ST_Point(-77.009003, 38.889931), 4326)
 , 0.01) ,
 pgr_pointToEdgeNode('ospr.ways', ST_SetSRID( ST_Point(-77.036545, 38.897096), 4326)
 , 0.01) , true) AS r
 LEFT JOIN ospr.ways AS w ON r.edge = w.gid;

`

If I run it under pgRouting 2.1 it takes 100 ms.

After I upgrade to pgRouting 2.2, it takes 9 seconds.

The simplified version putting in the actual nodes is also slow so pgr_pointToEdgeNode is not the problem.

`
SELECT r.seq, r.node, w.name As street, r.cost,
( SUM(w.length_m) OVER(ORDER BY r.seq) )::numeric(10,2) As dist_m
 FROM pgr_dijkstra('SELECT gid AS id,
 source,
 target,
 cost, reverse_cost
 FROM ospr.ways',
 11280,
14141 , true) AS r
 LEFT JOIN ospr.ways AS w ON r.edge = w.gid;

`

To test I did this:

`
DROP EXTENSION IF EXISTS pgrouting;
CREATE EXTENSION pgrouting VERSION "2.2.0";

-- run the query -- takes 9 seconds

DROP EXTENSION IF EXISTS pgrouting;
CREATE EXTENSION pgrouting VERSION "2.1.0";

--rerun the query takes 90-100ms

`

I repeated this a couple of times with similar results.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
This was testing with 

` PostgreSQL 9.5.1, compiled by Visual C++ build 1800, 64-bit
POSTGIS="2.3.0dev r14758" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.1, released 2015/09/15" LIBXML="2.7.8" LIBJSON="0.12" RASTER

`

But I also tested with PostGIS 2.2.1 with same results.

pgRouting 2.2.0 develop version - (2.2.0,pgrouting-2.2.0-beta1,f82dff3,develop,1.59.0)

**Comment by cvvergara** [comment]
@robe2 
I made this gist:
https://gist.github.com/cvvergara/dfe41b7d566536102df3
that use when testing performance (usually I have to modify it a little, but its my guide).
That is for at least run the query n times. (when I test I run it at least 30 times to get enough degrees of freedom for an statistical analysis)
Can you give it a try?

**Comment by woodbri** [comment]
Do you need to worry about cached results if you run it multiple times? which would skew the the time in favor of the cached response vs the actual compute time? I think this is not an issue for functions declared volatile but it would for functions declared stable or immutable.

**Comment by cvvergara** [comment]
@robe2 , I pushed hotfix/issue526
can you see if the changes I made make a difference?

**Comment by robe2** [comment]
Vicki,

Would it be a bother to push this to jenkins branch or even develop.  My dev environment for pgRouting  is a bit of a mess and I'd have to setup yet another job to follow this hot fix which is almost as much trouble as fixing my dev environment.  If you push it to either of those then winnie will make a build I can just copy and test with.

**Comment by cvvergara** [comment]
@robe2 
The Jenkins runs starts from
[3723](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/3723)
to
[3727](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/3727)

**Comment by robe2** [comment]
Should the hash have changed?  I still have the same hash, and sadly still same issue. 9 seconds to run.

Stats query output for:

`select * from public.statsQuery(10,3, 'pgr_dijkstra(',
'SELECT gid AS id,
 source,
 target,
 cost, reverse_cost
 FROM ospr.ways',
 ', 11280,14141, true)');`

Looks like:
` seq |                              sql                              |  lim   |         avgt         | err
-----+---------------------------------------------------------------+--------+----------------------+-----
   1 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|      1 | 0.000666666666666667 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 1 ) as _b', 11280,14141, true)          |        |                      |
   2 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|     10 | 0.000333666666666667 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 10 ) as _b', 11280,14141, true)         |        |                      |
   3 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|    100 | 0.000333333333333333 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 100 ) as _b', 11280,14141, true)        |        |                      |
   4 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|   1000 |  0.00166666666666667 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 1000 ) as _b', 11280,14141, true)       |        |                      |
   5 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|  10000 |   0.0153343333333333 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 10000 ) as _b', 11280,14141, true)      |        |                      |
   6 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 100000 |     9.69122066666667 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 100000 ) as _b', 11280,14141, true)     |        |                      |
   7 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 200000 |     9.81422833333333 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 200000 ) as _b', 11280,14141, true)     |        |                      |
   8 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 300000 |     10.0502413333333 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 300000 ) as _b', 11280,14141, true)     |        |                      |
   9 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 400000 |             9.702555 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 400000 ) as _b', 11280,14141, true)     |        |                      |
  10 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 500000 |     9.68788733333333 |
     |  source,                                                     +|        |                      |
     |  target,                                                     +|        |                      |
     |  cost, reverse_cost                                          +|        |                      |
     |  FROM ospr.ways limit 500000 ) as _b', 11280,14141, true)     |        |                      |
(10 rows)
`

For 2.1 looks like:

`seq |                              sql                              |  lim   |         avgt         | err
----+---------------------------------------------------------------+--------+----------------------+-----
  1 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|      1 |  0.00133333333333333 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 1 ) as _b', 11280,14141, true)          |        |                      |
  2 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|     10 |             0.000667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 10 ) as _b', 11280,14141, true)         |        |                      |
  3 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|    100 | 0.000666666666666667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 100 ) as _b', 11280,14141, true)        |        |                      |
  4 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|   1000 |  0.00166666666666667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 1000 ) as _b', 11280,14141, true)       |        |                      |
  5 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+|  10000 |   0.0146673333333333 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 10000 ) as _b', 11280,14141, true)      |        |                      |
  6 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 100000 |             0.052003 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 100000 ) as _b', 11280,14141, true)     |        |                      |
  7 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 200000 |   0.0516696666666667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 200000 ) as _b', 11280,14141, true)     |        |                      |
  8 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 300000 |   0.0553366666666667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 300000 ) as _b', 11280,14141, true)     |        |                      |
  9 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 400000 |             0.054003 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 400000 ) as _b', 11280,14141, true)     |        |                      |
 10 | select * from pgr_dijkstra(' select * from (SELECT gid AS id,+| 500000 |   0.0516696666666667 |
    |  source,                                                     +|        |                      |
    |  target,                                                     +|        |                      |
    |  cost, reverse_cost                                          +|        |                      |
    |  FROM ospr.ways limit 500000 ) as _b', 11280,14141, true)     |        |                      |
10 rows)
`

**Comment by cvvergara** [comment]
@robe2 
about the hash..  I don't know
I have my hook for when I do a commit and we are one behind
and the code is still in hotfix/issue526
I went to modify in Jekins what was going to be tested
I didn't merge into develop nor dev-2.2 nor master. because first I need to know if the fix I tried works.

I also made this [performance test for dijstra](https://github.com/pgRouting/pgrouting/tree/hotfix/issue526/src/linecommand/src/performance/dijkstra) code

cd /src/linecommand/src/performance/dijkstra
make
pgRouting -d <nameofdatabase>
it will ask you for the query
then it will ask you if the graph is directed or undirected
then you can run dijkstra by typing:
dijkstra from 11280 to 14141

that what it will do, will tell you the time it takes only to run the algorithm
the loading data, printing output, communication with the database, are 100% ignored.
(not sure if that code will work on 2.1)

**Comment by robe2** [comment]
Not following you. I was testing the jenkins build.  Should that not have your changes

**Comment by cvvergara** [comment]
@robe2 
I finnaly found what was wrong, its a very strange bug:
When initializing the boost's graph, it reads a parameter of how many nodes it has:
Graph(N)
so for 2.2 I gave an estimated value for the numbers of nodes, instead of 1, (that is the value I used in 2.1) so I am giving again the 1.
here are the time results I am getting:
```
drop extension pgrouting; create extension pgrouting;
\c
\set VERBOSITY terse
SET client_min_messages to DEBUG1;
SELECT pgr_version();
                       pgr_version                       
---------------------------------------------------------
 (2.2.0,pgrouting-2.2.0-beta2dev,f82dff3,develop,1.54.0)
(1 row)

dc_area=# SELECT * from pgr_dijkstra('SELECT gid AS id,
 source,  target,  cost, reverse_cost
 FROM ospr.ways',
 11280, 14141, true);
DEBUG:  Elapsed time for  reading Edges: 0.033935sec = (53296.000000 - 19361.000000) / CLOCKS_PER_SEC 
DEBUG:  Elapsed time for  processing Dijkstra one to one: 0.086655sec = (140145.000000 - 53490.000000) / CLOCKS_PER_SEC
```

[travis](https://travis-ci.org/pgRouting/pgrouting/builds/116154870) runs are ok.

## jenkins
[jenkins](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_branch_develop/46/) matrix.

Note, on this [develop matrix in Jenkins](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_branch_develop/46/)  it never finds postGIS, so the tests are never executed:
Example in [2702](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/2702/console]:
```
RUNNING: algorithm-tester.pl -pgver 9.5 -pgisver 2.2.2dev -pgport 10564 -ignorenotice -clean
dropdb: database removal failed: ERROR:  database "pgr_test__db__test" does not exist
ERROR:  could not load library "e:/jenkins/postgresql/rel/pg9.5w64gcc48/lib/postgis-2.2.dll": The specified procedure could not be found.
```

so I modified  this [jenkins matrix in Jenkins](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_branch_jenkins/) to execute branch develop and tests runs fine, for example
in (3761)[http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/3761/console]

**Comment by robe2** [comment]
Thanks I'll give it a try next change I get.  Bogged down for next couple of days.  I also strted installing pgTap but haven't finished that yet.  Hope to be done with all of these by this weekend.

**Comment by robe2** [comment]
Did a test with my dc data and looks good now back to 71-100ms.

**Comment by cvvergara** [comment]
@robe2 
thanks for confirmation, I will close this issue when beta2 is released

**Comment by cvvergara** [comment]
fixed in Tag pgrouting-2.2.0-RC1
